
import { Company } from './types';

export const AVAILABLE_STOCKS: Company[] = [
  // Existing Stocks
  { id: 'googl', symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', description: 'A multinational technology conglomerate. (Parent of Google)', marketCap: '2.1T', peRatio: 25, revenue: '300B', logoUrl: 'https://picsum.photos/seed/googl/40/40' },
  { id: 'msft', symbol: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology', description: 'A multinational technology corporation.', marketCap: '3.1T', peRatio: 38, revenue: '220B', logoUrl: 'https://picsum.photos/seed/msft/40/40' },
  { id: 'aapl', symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', description: 'Designs, manufactures, and markets consumer electronics and software.', marketCap: '2.6T', peRatio: 27, revenue: '380B', logoUrl: 'https://picsum.photos/seed/aapl/40/40' },
  { id: 'amzn', symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'E-commerce', description: 'Focuses on e-commerce, cloud computing, and AI.', marketCap: '1.9T', peRatio: 50, revenue: '550B', logoUrl: 'https://picsum.photos/seed/amzn/40/40' },
  { id: 'tsla', symbol: 'TSLA', name: 'Tesla, Inc.', sector: 'Automotive', description: 'Designs and manufactures electric vehicles and clean energy solutions.', marketCap: '550B', peRatio: 40, revenue: '90B', logoUrl: 'https://picsum.photos/seed/tsla/40/40' },
  { id: 'openai', symbol: 'OPENAI', name: 'OpenAI (Conceptual)', sector: 'Artificial Intelligence', description: 'An AI research and deployment company. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/openai/40/40' },

  // Newly Added Stocks from User's List (Selection)
  { id: 'flipkart', symbol: 'FLPKT', name: 'Flipkart (Conceptual)', sector: 'E-commerce', description: 'Major Indian e-commerce platform. (Owned by Walmart, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/FLPKT/40/40' },
  { id: 'nykaa', symbol: 'NYKAA.NS', name: 'FSN E-Commerce Ventures (Nykaa)', sector: 'E-commerce', description: 'Indian e-commerce company for beauty and wellness products.', marketCap: '500B INR', peRatio: 700, revenue: '60B INR', logoUrl: 'https://picsum.photos/seed/NYKAA.NS/40/40' },
  { id: 'meesho', symbol: 'MEESHO', name: 'Meesho (Conceptual)', sector: 'E-commerce', description: 'Indian social commerce platform. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/MEESHO/40/40' },
  { id: 'lenskart', symbol: 'LENSK', name: 'Lenskart (Conceptual)', sector: 'Retail', description: 'Indian eyewear retail chain. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/LENSK/40/40' },
  { id: 'phonepe', symbol: 'PHONEPE', name: 'PhonePe (Conceptual)', sector: 'FinTech', description: 'Indian digital payments platform. (Owned by Walmart, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/PHONEPE/40/40' },
  { id: 'cred', symbol: 'CREDAPP', name: 'CRED (Conceptual)', sector: 'FinTech', description: 'Indian credit card bill payment platform. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/CREDAPP/40/40' },
  { id: 'razorpay', symbol: 'RAZORP', name: 'Razorpay (Conceptual)', sector: 'FinTech', description: 'Indian payment gateway provider. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/RAZORP/40/40' },
  { id: 'groww', symbol: 'GROWWAPP', name: 'Groww (Conceptual)', sector: 'FinTech', description: 'Indian investment platform. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/GROWWAPP/40/40' },
  { id: 'zoho', symbol: 'ZOHOCORP', name: 'Zoho Corporation (Conceptual)', sector: 'SaaS', description: 'Indian multinational technology company making web-based business tools. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/ZOHOCORP/40/40' },
  { id: 'freshworks', symbol: 'FRSH', name: 'Freshworks Inc.', sector: 'SaaS', description: 'Customer engagement software company.', marketCap: '3.5B', peRatio: undefined, revenue: '600M', logoUrl: 'https://picsum.photos/seed/FRSH/40/40' },
  { id: 'byjus', symbol: 'BYJUS', name: 'BYJU\'S (Conceptual)', sector: 'EdTech', description: 'Indian multinational educational technology company. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/BYJUS/40/40' },
  { id: 'delhivery', symbol: 'DELHIVERY.NS', name: 'Delhivery Ltd.', sector: 'Logistics', description: 'Indian logistics and supply chain company.', marketCap: '300B INR', peRatio: undefined, revenue: '80B INR', logoUrl: 'https://picsum.photos/seed/DELHIVERY.NS/40/40' },
  { id: 'zomato', symbol: 'ZOMATO.NS', name: 'Zomato Ltd.', sector: 'Food Delivery', description: 'Indian multinational restaurant aggregator and food delivery company.', marketCap: '1.5T INR', peRatio: 120, revenue: '100B INR', logoUrl: 'https://picsum.photos/seed/ZOMATO.NS/40/40' },
  { id: 'tcs', symbol: 'TCS.NS', name: 'Tata Consultancy Services Ltd.', sector: 'IT Services', description: 'Indian multinational IT services and consulting company.', marketCap: '14T INR', peRatio: 30, revenue: '2.3T INR', logoUrl: 'https://picsum.photos/seed/TCS.NS/40/40' },
  { id: 'infosys', symbol: 'INFY.NS', name: 'Infosys Ltd.', sector: 'IT Services', description: 'Indian multinational IT services and consulting company.', marketCap: '6T INR', peRatio: 25, revenue: '1.5T INR', logoUrl: 'https://picsum.photos/seed/INFY.NS/40/40' },
  { id: 'wipro', symbol: 'WIPRO.NS', name: 'Wipro Ltd.', sector: 'IT Services', description: 'Indian multinational IT, consulting and business process services company.', marketCap: '2.5T INR', peRatio: 20, revenue: '900B INR', logoUrl: 'https://picsum.photos/seed/WIPRO.NS/40/40' },
  { id: 'hcltech', symbol: 'HCLTECH.NS', name: 'HCL Technologies Ltd.', sector: 'IT Services', description: 'Indian multinational IT services and consulting company.', marketCap: '3.8T INR', peRatio: 26, revenue: '1T INR', logoUrl: 'https://picsum.photos/seed/HCLTECH.NS/40/40' },
  { id: 'techm', symbol: 'TECHM.NS', name: 'Tech Mahindra Ltd.', sector: 'IT Services', description: 'Indian multinational IT services and consulting company.', marketCap: '1.3T INR', peRatio: 28, revenue: '500B INR', logoUrl: 'https://picsum.photos/seed/TECHM.NS/40/40' },
  { id: 'ltim', symbol: 'LTIM.NS', name: 'LTIMindtree Ltd.', sector: 'IT Services', description: 'Indian multinational IT services and consulting company.', marketCap: '1.5T INR', peRatio: 33, revenue: '350B INR', logoUrl: 'https://picsum.photos/seed/LTIM.NS/40/40' },
  { id: 'persistent', symbol: 'PERSISTENT.NS', name: 'Persistent Systems Ltd.', sector: 'IT Services', description: 'Indian multinational technology services company.', marketCap: '600B INR', peRatio: 55, revenue: '90B INR', logoUrl: 'https://picsum.photos/seed/PERSISTENT.NS/40/40' },
  { id: 'mmyt', symbol: 'MMYT', name: 'MakeMyTrip Limited', sector: 'Travel Technology', description: 'Indian online travel company.', marketCap: '8B', peRatio: 100, revenue: '700M', logoUrl: 'https://picsum.photos/seed/MMYT/40/40' },
  { id: 'ibm', symbol: 'IBM', name: 'IBM Corp.', sector: 'Technology', description: 'International Business Machines Corporation, a global tech company.', marketCap: '150B', peRatio: 20, revenue: '60B', logoUrl: 'https://picsum.photos/seed/IBM/40/40' },
  { id: 'sap', symbol: 'SAP', name: 'SAP SE', sector: 'Software', description: 'German multinational software corporation.', marketCap: '200B EUR', peRatio: 30, revenue: '30B EUR', logoUrl: 'https://picsum.photos/seed/SAP/40/40' },
  { id: 'oracle', symbol: 'ORCL', name: 'Oracle Corp.', sector: 'Software', description: 'American multinational computer technology corporation.', marketCap: '330B', peRatio: 35, revenue: '50B', logoUrl: 'https://picsum.photos/seed/ORCL/40/40' },
  { id: 'adbe', symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Software', description: 'American multinational computer software company.', marketCap: '200B', peRatio: 30, revenue: '19B', logoUrl: 'https://picsum.photos/seed/ADBE/40/40' },
  { id: 'crm', symbol: 'CRM', name: 'Salesforce, Inc.', sector: 'SaaS', description: 'American cloud-based software company.', marketCap: '220B', peRatio: 70, revenue: '35B', logoUrl: 'https://picsum.photos/seed/CRM/40/40' },
  { id: 'csco', symbol: 'CSCO', name: 'Cisco Systems, Inc.', sector: 'Technology', description: 'American multinational technology conglomerate.', marketCap: '190B', peRatio: 15, revenue: '55B', logoUrl: 'https://picsum.photos/seed/CSCO/40/40' },
  { id: 'intc', symbol: 'INTC', name: 'Intel Corporation', sector: 'Semiconductors', description: 'American multinational corporation and technology company.', marketCap: '130B', peRatio: 30, revenue: '55B', logoUrl: 'https://picsum.photos/seed/INTC/40/40' },
  { id: 'nvda', symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Semiconductors', description: 'American multinational technology company, designs GPUs.', marketCap: '2.2T', peRatio: 70, revenue: '60B', logoUrl: 'https://picsum.photos/seed/NVDA/40/40' },
  { id: 'pidilitind', symbol: 'PIDILITIND.NS', name: 'Pidilite Industries Ltd.', sector: 'Chemicals', description: 'Indian adhesives manufacturing company (Fevicol, Dr. Fixit).', marketCap: '1.4T INR', peRatio: 90, revenue: '120B INR', logoUrl: 'https://picsum.photos/seed/PIDILITIND.NS/40/40' },
  { id: 'asianpaint', symbol: 'ASIANPAINT.NS', name: 'Asian Paints Ltd.', sector: 'Paints', description: 'Indian multinational paint company.', marketCap: '2.7T INR', peRatio: 50, revenue: '350B INR', logoUrl: 'https://picsum.photos/seed/ASIANPAINT.NS/40/40' },
  { id: 'bergepaint', symbol: 'BERGEPAINT.NS', name: 'Berger Paints India Ltd.', sector: 'Paints', description: 'Indian multinational paint company.', marketCap: '550B INR', peRatio: 55, revenue: '100B INR', logoUrl: 'https://picsum.photos/seed/BERGEPAINT.NS/40/40' },
  { id: 'kansainer', symbol: 'KANSAINER.NS', name: 'Kansai Nerolac Paints Ltd.', sector: 'Paints', description: 'Indian paint company, subsidiary of Kansai Paint, Japan.', marketCap: '220B INR', peRatio: 40, revenue: '75B INR', logoUrl: 'https://picsum.photos/seed/KANSAINER.NS/40/40' },
  { id: 'havells', symbol: 'HAVELLS.NS', name: 'Havells India Ltd.', sector: 'Electrical Equipment', description: 'Indian electrical equipment company.', marketCap: '1T INR', peRatio: 70, revenue: '180B INR', logoUrl: 'https://picsum.photos/seed/HAVELLS.NS/40/40' },
  { id: 'crompton', symbol: 'CROMPTON.NS', name: 'Crompton Greaves Consumer Electricals Ltd.', sector: 'Consumer Durables', description: 'Indian electrical equipment company.', marketCap: '200B INR', peRatio: 35, revenue: '70B INR', logoUrl: 'https://picsum.photos/seed/CROMPTON.NS/40/40' },
  { id: 'voltas', symbol: 'VOLTAS.NS', name: 'Voltas Ltd.', sector: 'Consumer Durables', description: 'Indian home appliances company (Tata Group).', marketCap: '450B INR', peRatio: 60, revenue: '100B INR', logoUrl: 'https://picsum.photos/seed/VOLTAS.NS/40/40' },
  { id: 'bajajelec', symbol: 'BAJAJELEC.NS', name: 'Bajaj Electricals Ltd.', sector: 'Consumer Durables', description: 'Indian consumer electrical equipment manufacturing company.', marketCap: '100B INR', peRatio: 50, revenue: '50B INR', logoUrl: 'https://picsum.photos/seed/BAJAJELEC.NS/40/40' },
  { id: 'ttkprestige', symbol: 'TTKPRESTIG.NS', name: 'TTK Prestige Ltd.', sector: 'Consumer Durables', description: 'Indian kitchen appliances manufacturer.', marketCap: '100B INR', peRatio: 40, revenue: '30B INR', logoUrl: 'https://picsum.photos/seed/TTKPRESTIG.NS/40/40' },
  { id: 'bel', symbol: 'BEL.NS', name: 'Bharat Electronics Limited', sector: 'Aerospace & Defense', description: 'Indian state-owned aerospace and defence electronics company.', marketCap: '1.7T INR', peRatio: 45, revenue: '180B INR', logoUrl: 'https://picsum.photos/seed/BEL.NS/40/40' },
  { id: 'atherenergy', symbol: 'ATHER', name: 'Ather Energy (Conceptual)', sector: 'Automotive', description: 'Indian electric vehicle company. (Private, conceptual listing)', marketCap: 'N/A', peRatio: undefined, revenue: 'N/A', logoUrl: 'https://picsum.photos/seed/ATHER/40/40' },
];

export const GEMINI_TEXT_MODEL = 'gemini-2.5-flash-preview-04-17';
export const GEMINI_IMAGE_MODEL = 'imagen-3.0-generate-002';

export const MOCK_API_KEY = 'mock-api-key-for-development'; // Placeholder if process.env.API_KEY is not set
